[package]
name = "two_colours_grid"
version = "1.0.0"
authors = ["Todor Videv <videvt@gmail.com>"]
edition = "2018"

[dependencies]
doodles_lib = { path = "../doodles_lib" }
nannou = "0.15.0"
rand = "0.8.3"
